name: Create challenge from issue form

on:
  issues:
    types:
      - opened
      - edited

jobs:
  main:
    # rerun automation on edits, but only by trusted users to limit git history noise
    if: github.event.action == 'opened' || github.actor == github.repository_owner
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x
          cache: pip

      - uses: zentered/issue-forms-body-parser@3dc7e926aa8e97596968cc8117801514d6c081bd # v3.0.0
        id: form

      - name: Slugify challenge name
        id: slugify
        uses: rlespinasse/slugify-value@v1.4.0
        with:
          key: title
          value: ${{ github.event.issue.title }}

      - name: Make challenge directory and metadata
        id: chal
        run: |
          directory="${{ env.category }}/${{ steps.slugify.outputs.slug }}"
          mkdir -p $directory
          echo "directory=$directory" >> $GITHUB_OUTPUT
          echo "category=${{ env.category }}" >> $GITHUB_OUTPUT
        env:
          category: ${{ fromJSON(steps.form.outputs.data).category.text }}

      - name: Create writeup
        run: printf "%s" "$data" > ${{ steps.chal.outputs.directory }}/README.md
        env:
          data: ${{ fromJSON(steps.form.outputs.data).writeup.text }}

      - name: Parse issue form to jinja2 data file
        run: printf "%s" "$data" | jq 'with_entries(.value = .value.text)' > data.json
        env:
          data: ${{ steps.form.outputs.data }}

      - name: Render challenge.yml
        run: |
          pip install jinja2-cli
          jinja2 .github/challenge.jinja2 data.json \
          --outfile "${{ steps.chal.outputs.directory }}/challenge.yml" \
          -D name="${{ github.event.issue.title }}"
          rm data.json

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: patch-${{ github.event.issue.number }}
          title: ${{ env.title }}
          body: "Closes #${{ github.event.issue.number }}"
          commit-message: ${{ env.title }}
          sign-commits: true
        env:
          title: "chals(${{ steps.chal.outputs.category }}): add ${{ steps.slugify.outputs.slug }}"

      - uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            [Click here to upload challenge files](${{ format('{0}/{1}/upload/patch-{2}/{3}',
              github.server_url,
              github.repository,
              github.event.issue.number,
              steps.chal.outputs.directory
            )}})
