name: Create challenge from issue form

on:
  issues:
    types:
      - opened

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.x
          cache: pip

      - uses: zentered/issue-forms-body-parser@93bd9fdcb3679be1889d2006e9c2cf496899402e # v2.2.0
        id: form

      - name: Slugify challenge name
        id: slugify
        uses: rlespinasse/slugify-value@a4879db1eb3db9bbee01dca36f98a8236c2b8239 # v1.4.0
        with:
          key: title
          value: ${{ github.event.issue.title }}

      - name: Make challenge directory and metadata
        id: chal
        run: |
          directory="${{ env.category }}/${{ steps.slugify.outputs.slug }}"
          mkdir -p $directory
          echo "directory=$directory" >> $GITHUB_OUTPUT
          echo "category=${{ env.category }}" >> $GITHUB_OUTPUT
        env:
          category: ${{ fromJSON(steps.form.outputs.data).category.text }}

      - name: Create writeup
        run: printf "%s" "$data" > ${{ steps.chal.outputs.directory }}/README.md
        env:
          data: ${{ fromJSON(steps.form.outputs.data).writeup.text }}

      - name: Parse issue form to jinja2 data file
        run: printf "%s" "$data" | jq 'with_entries(.value = .value.text)' > data.json
        env:
          data: ${{ steps.form.outputs.data }}

      - name: Render challenge.yml
        run: |
          pip install jinja2-cli
          jinja2 .github/challenge.jinja2 data.json \
          --outfile "${{ steps.chal.outputs.directory }}/challenge.yml" \
          -D name="${{ github.event.issue.title }}"
          rm data.json

      - uses: peter-evans/create-pull-request@a4f52f8033a6168103c2538976c07b467e8163bc # v6.0.1
        with:
          branch: patch-${{ github.event.issue.number }}
          title: ${{ env.title }}
          body: "Closes #${{ github.event.issue.number }}"
          commit-message: ${{ env.title }}
        env:
          title: "chals(${{ steps.chal.outputs.category }}): add ${{ steps.slugify.outputs.slug }}"

      - uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            [Click here to upload challenge files](${{ format('{0}/{1}/upload/patch-{2}/{3}',
              github.server_url,
              github.repository,
              github.event.issue.number,
              steps.chal.outputs.directory
            )}})
